service: cart-service

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  service: cart-service
  tableName: ${self:custom.stage}-cart
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

package:
  individually: true

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1
  tags:
    app: ${self:custom.service}
    env: ${self:custom.stage}
  deploymentBucket:
    name: shop-service-artifacts
  apiGateway: #shared Gateway setting
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-sharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-sharedGW-rootResourceId
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-east-1:#{AWS::AccountId}:secret:/external/*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  getCart:
    handler: functions/get/handler.handler
    events:
      - http:
          path: cart/{cartid}
          method: get
          cors: true
          request:
            parameters:
              paths:
                cartid: true
  createCart:
    handler: functions/create/handler.handler
    events:
      - http:
          path: cart
          method: post
          cors: true

  addCartItem:
    handler: functions/cartItem/add/handler.handler
    events:
      - http:
          path: cart/{cartid}/addItem
          method: post
          cors: true

  updateCartItem:
    handler: functions/cartItem/update/handler.handler
    events:
      - http:
          path: cart/{cartid}/updateItem
          method: post
          cors: true

  deleteCartItem:
    handler: functions/cartItem/delete/handler.handler
    events:
      - http:
          path: cart/{cartid}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                cartid: true
  deleteCart:
    handler: functions/delete/handler.handler
    events:
      - http:
          path: cart/{cartid}
          method: delete
          cors: true
  
  checkoutCart:
    handler: functions/checkout/index.handler
    events:
      - http:
          path: cart/{cartid}/checkout
          method: post
          cors: true
    environment:
      STRIPE_API_KEY: ${env:STRIPE_API_KEY}

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}