service: cart-service

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-cart
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

# package:
#   individually: true
#   excludeDevDependencies: false

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket:
    name: shop-service-artifacts
    serverSideEncryption: AES256
  apiGateway: #shared Gateway setting
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-sharedGW-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-sharedGW-rootResourceId
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  getCart:
    runtime: nodejs12.x
    handler: functions/get.handler
    events:
      - http:
          path: cart/{cartid}
          method: get
          cors: true
  createCart:
    runtime: nodejs12.x
    handler: functions/create.handler
    events:
      - http:
          path: cart
          method: post
          cors: true

  addCartItem:
    runtime: nodejs12.x
    handler: functions/cartItem/add.handler
    events:
      - http:
          path: cart/{cartid}/addItem
          method: post
          cors: true

  updateCartItem:
    runtime: nodejs12.x
    handler: functions/cartItem/update.handler
    events:
      - http:
          path: cart/{cartid}/updateItem
          method: post
          cors: true

  deleteCartItem:
    runtime: nodejs12.x
    handler: functions/cartItem/delete.handler
    events:
      - http:
          path: cart/{cartid}/deleteItem
          method: delete
          cors: true

  deleteCart:
    runtime: nodejs12.x
    handler: functions/delete.handler
    events:
      - http:
          path: cart/{cartid}
          method: delete
          cors: true

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}