service: api-shared-gateway
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
custom:
  stage: ${opt:stage, self:provider.stage}
resources:
  Resources:
    SharedGW:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.stage}-sharedGW
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: SharedGW
      Export:
        Name: ${self:custom.stage}-sharedGW-restApiId
    apiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - SharedGW
          - RootResourceId
      Export:
        Name: ${self:custom.stage}-sharedGW-rootResourceId