service: search-products
provider:
  name: aws
  runtime: nodejs12.x
  # apiName: custom-api-name # Use a custom name for the API Gateway API
  deploymentBucket:
    name: shop-elguru-artifacts
    blockPublicAccess: true
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - es:*
      Resource:
        - '*'
      Condition:
        IpAddress:
          aws:sourceIp:
            - "207.181.207.119"
    - Effect: Allow
      Action:
        - es:ESHttpPost
        - es:ESHttpHead
        - es:ESHttpPut
        - es:ESHttpDelete
        - es:ESHttpGet
      Resource:
        - { "Fn::GetAtt": ["ElasticSearchInstance", "DomainArn"] }
        - { "Fn::Join": ["", ["Fn::GetAtt": ["ElasticSearchInstance", "DomainArn"], "/*"]] }

functions:
  elasticsearch-dynamodb:
    handler: dynamodb-stream-elasticsearch.stream
    environment:
      ES_ENDPOINT:
        Fn::GetAtt: [ ElasticSearchInstance , DomainEndpoint ]
      # INDEX: allproducts
      # TYPE: allproducts
    events:
      - stream:
          type: dynamodb
          batchSize: 100
          startingPosition: LATEST
          enabled: true
          arn: arn:aws:dynamodb:us-east-1:677660837407:table/products/stream/2020-01-02T02:28:11.581
resources:
  Resources:
    ElasticSearchInstance:
      Type: AWS::Elasticsearch::Domain
      Properties:
        DomainName: products-es
        EBSOptions:
          EBSEnabled: true
          VolumeType: standard
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: 6.8
Outputs:
  DomainArn:
    Value: !GetAtt ElasticsearchDomain.DomainArn
  DomainEndpoint:
    Value: !GetAtt ElasticsearchDomain.DomainEndpoint
  SecurityGroupId:
    Value: !Ref mySecurityGroup
  SubnetId:
    Value: !Ref subnet